name: Classroom Workflow

on:
  push:
    paths:
      - 'scripts/routers/prediction.py'
  pull_request:
    paths:
      - 'scripts/schema/response.py'

  workflow_dispatch:
    inputs:
      runner:
        description: "Who runs this workflow?"
        required: true
jobs:
  classroom_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Print latest content
        run: |
          if [[ "$GITHUB_EVENT_NAME" == "push" ]]; then
            cat scripts/routers/prediction.py
          elif [[ "$GITHUB_EVENT_NAME" == "pull_request" ]]; then
            cat scripts/schema/response.py
          else
            echo ${{ inputs.runner }}
          fi