name: test_workflow

on: 
  push:
    branches:
      - main
  pull_request:
    paths:
      - 'scripts/**/*'
      - 'test/**/*'
      - requirements.txt
      - '.github/**'
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
      - name: Set up cache
        uses: actions/cache@v3
        with:
          paths: |
            ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run tests
        run: |
          export PYTHONPATH="${PYTHONPATH}:$(pwd)/scripts"
          # echo "PYTHONPATH=$GITHUB_WORKSPACE/src:$PYTHONPATH" >> $GITHUB_ENV
          pytest --cov
  
  deploy_job:
    runs-on: ubuntu-latest
    needs: test
    if: startsWith(github.ref, 'refs/pull/')
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: docker.io/${{ vars.DOCKER_USERNAME }}/car-price-prediction-app:PULL-${{ github.event.number }}
      - name: Login to GCP 
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}
      - name: Deploy to GCP 
        uses: google-github-actions/deploy-cloudrun@v1
        with:
          service: mlops-course-app
          image: 'docker.io/${{ vars.DOCKER_USERNAME }}/car-price-prediction-app:PULL-${{ github.event.number }}'
          region: us-central1
          platform: managed
  
  deploy_main:
    needs: test
    if: startsWith(github.ref, 'refs/heads/main')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          push: true
          context: .
          # get 9 first characters of the sha
          tags: docker.io/${{ vars.DOCKER_USERNAME }}/car-price-prediction-app:${GITHUB_SHA:0:9}
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v3
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}
      - name: Deploy to Google Cloud Run
        uses: google-github-actions/deploy-cloudrun@v3
        with:
          service: 'mlops-course-app'
          image: 'docker.io/${{ vars.DOCKER_USERNAME }}/car-price-prediction-app:${GITHUB_SHA:0:9}'
